version: '3'

services:

  app:
    image: node:alpine
    build: ../fec-graviton-legacy/
    # environment:
    #   POSTGRES_HOST: postgres
    #   POSTGRES_USER: admin
    #   POSTGRES_PASSWORD: sdc
    #   POSTGRES_DB: qa
    volumes:
      - ../fec-graviton-legacy/:/app
    ports:
      - "3000:3000"
    working_dir: /app

  api:
    restart: always
    build:
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sdc
      POSTGRES_DB: qa
    ports:
      - "8080:8080"
    working_dir: /api

  postgres:
    image: postgres:15.2
    build:
      context: ./postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sdc
      POSTGRES_DB: qa
      # PGDATA: /tmp
    volumes:
      - qa-db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    command: >
      -c max_wal_size=10GB

volumes:
  qa-db-data: