version: '3.7'
services:
  nodeserver:
    build:
      context: ./app
    ports:
      - "3000:3000"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  postgres:
    build:
      context: ./postgres
    ports:
      - "3076:3076"