version: '3'

services:

  app:
    image: node:alpine
    build: ../fec-graviton-legacy/
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sdc
      POSTGRES_DB: qa
    volumes:
      - ../fec-graviton-legacy/:/app
    ports:
      - "3000:3000"
    working_dir: /app
  # nginx:
  #   restart: always
  #   build:
  #     context: ./nginx
  #   ports:
  #     - "80:80"

  postgres:
    image: postgres:latest
    build:
      context: ./postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sdc
      POSTGRES_DB: qa
      # PGDATA: /tmp
    volumes:
      - qa-db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  qa-db-data: