version: '3.7'
services:
  nodeserver:
    build:
      context: ./app
    ports:
      - "3000:3000"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  postgres:
    build:
      context: ./postgres
    restart: always
    environment:
      POSTGRES_DB: qa
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sdc
      PGDATA: /tmp
    volumes:
      - qa-db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  qa-db-data:
    name: qa-db-data